name: Build & Test

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
      - develop

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      pull-requests: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Validate Gradle Wrapper
        uses: gradle/wrapper-validation-action@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: 21

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v3

      - name: Set up Android SDK
        uses: android-actions/setup-android@v3

      - name: Set execute permissions for gradlew
        run: chmod +x ./gradlew

      - name: Detekt Verification
        run: ./gradlew detektAll

      - name: Upload SARIF to GitHub using the upload-sarif action
        uses: github/codeql-action/upload-sarif@v3
        if: success() || failure()
        with:
          sarif_file: app/build/reports/detekt/detekt.sarif
          category: lint

      - name: Run Unit Tests
        run: ./gradlew testDebugUnitTest